
# memes - audio

# pasta onde os audios estão localizados
PREFIX_FOLDER="$HOME/.commands/meme/audios"

# comando que executa o audio
AUDIO_COMM="afplay"


alias pain="${AUDIO_COMM} ${PREFIX_FOLDER}/Girei.mp3"
alias tosse="${AUDIO_COMM} ${PREFIX_FOLDER}/tosseVeia.mp3"
alias uol="${AUDIO_COMM} ${PREFIX_FOLDER}/uOOL.mp3"
alias pdm="${AUDIO_COMM} ${PREFIX_FOLDER}/pdm.mp3"
alias prb="${AUDIO_COMM} ${PREFIX_FOLDER}/PARABAINS.mp3"
alias dmad="${AUDIO_COMM} ${PREFIX_FOLDER}/2milanosdepois.mp3"
alias lgl="${AUDIO_COMM} ${PREFIX_FOLDER}/legal.mp3"
alias blc="${AUDIO_COMM} ${PREFIX_FOLDER}/bemloco.mp3"
alias empt="${AUDIO_COMM} ${PREFIX_FOLDER}/empolgante.mp3"
alias aiai="${AUDIO_COMM} ${PREFIX_FOLDER}/aiai.mp3"
alias cceb="${AUDIO_COMM} ${PREFIX_FOLDER}/cceb.mp3"
alias vfmb="${AUDIO_COMM} ${PREFIX_FOLDER}/vfmb.mp3"
alias chines="${AUDIO_COMM} ${PREFIX_FOLDER}/pqnaotrabaia.mpeg"
alias fdpoc="${AUDIO_COMM} ${PREFIX_FOLDER}/filadaputaoce.mp3"
alias kdoc="${AUDIO_COMM} ${PREFIX_FOLDER}/cadeoce.mp3"
alias pqntr="${AUDIO_COMM} ${PREFIX_FOLDER}/poquenaotrabaia.mp3"
alias tsc="${AUDIO_COMM} ${PREFIX_FOLDER}/vaitomasuagu.mp3"
alias enam="${AUDIO_COMM} ${PREFIX_FOLDER}/eunaoaguentomais.mp3"
alias acsl="${AUDIO_COMM} ${PREFIX_FOLDER}/claudiasentala.mp3"
alias srjb="${AUDIO_COMM} ${PREFIX_FOLDER}/serjaoBerranteiroMiauAuuh.mp3"
alias flw="${AUDIO_COMM} ${PREFIX_FOLDER}/mandeNoticias.mp3"
alias disg="${AUDIO_COMM} ${PREFIX_FOLDER}/digrassaa.mp3"
alias tstn="${AUDIO_COMM} ${PREFIX_FOLDER}/teoricamenteSimTeoricamenteNao.mp3"
alias ceb="${AUDIO_COMM} ${PREFIX_FOLDER}/ceehobichao.mp3"
alias cafe="${AUDIO_COMM} ${PREFIX_FOLDER}/cafezinho.mp3"
alias chtr="${AUDIO_COMM} ${PREFIX_FOLDER}/chavesTriste.mp3"
alias arnold="${AUDIO_COMM} ${PREFIX_FOLDER}/arnold.mp3"
alias entl="${AUDIO_COMM} ${PREFIX_FOLDER}/alborghetti.mp3"
alias uepa="${AUDIO_COMM} ${PREFIX_FOLDER}/uepa.mp3"
alias dlc="${AUDIO_COMM} ${PREFIX_FOLDER}/dilissa.mp3"
alias heman="${AUDIO_COMM} ${PREFIX_FOLDER}/hahaha_euVoBotaNaTuaBundaHeMan.mp3"
alias tuab="${AUDIO_COMM} ${PREFIX_FOLDER}/hahaha_euVoBotaNaTuaBunda.mp3"
alias galocego="${AUDIO_COMM} ${PREFIX_FOLDER}/galocego.mp3"
alias jubileu="${AUDIO_COMM} ${PREFIX_FOLDER}/jubileu.mp3"
alias tcdsv="${AUDIO_COMM} ${PREFIX_FOLDER}/tomaContaDaSuaVida.mp3"
alias jos="${AUDIO_COMM} ${PREFIX_FOLDER}/josoares.mp3"
alias taporra="${AUDIO_COMM} ${PREFIX_FOLDER}/taporrameno.mp3"
alias afdp="${AUDIO_COMM} ${PREFIX_FOLDER}/afdp.mp3"
alias abacaxi="${AUDIO_COMM} ${PREFIX_FOLDER}/abacaxi.mp3"
alias mdms="${AUDIO_COMM} ${PREFIX_FOLDER}/mdms.mp3"
alias tomei="${AUDIO_COMM} ${PREFIX_FOLDER}/tomeinocu.mp3"
alias globor="${AUDIO_COMM} ${PREFIX_FOLDER}/globorurarl.mp3"
alias selasque="${AUDIO_COMM} ${PREFIX_FOLDER}/selasque.mp3"
alias miranha="${AUDIO_COMM} ${PREFIX_FOLDER}/miranha.mp3"
alias fail1="${AUDIO_COMM} ${PREFIX_FOLDER}/fail1.mp3"
alias fail2="${AUDIO_COMM} ${PREFIX_FOLDER}/fail2.mp3"
alias arrea="${AUDIO_COMM} ${PREFIX_FOLDER}/arrea.mp3"
alias borabill="${AUDIO_COMM} ${PREFIX_FOLDER}/borabill.mp3"
alias borafi="${AUDIO_COMM} ${PREFIX_FOLDER}/borafi.mp3"
alias boramuie="${AUDIO_COMM} ${PREFIX_FOLDER}/boramuie.mp3"
alias tchau="${AUDIO_COMM} ${PREFIX_FOLDER}/tchaupessoal.mp3"
alias valemil="${AUDIO_COMM} ${PREFIX_FOLDER}/valendomilreais.mp3"
alias valeum="${AUDIO_COMM} ${PREFIX_FOLDER}/valendoummilhao.mp3"
alias vcent="${AUDIO_COMM} ${PREFIX_FOLDER}/voceentendeu.mp3"
alias possop="${AUDIO_COMM} ${PREFIX_FOLDER}/possoperguntar.mp3"
alias toguro="${AUDIO_COMM} ${PREFIX_FOLDER}/toguro.mp3"
alias sqlvh="${AUDIO_COMM} ${PREFIX_FOLDER}/sentaquelavemhistoria.mp3"
alias marilene="${AUDIO_COMM} ${PREFIX_FOLDER}/marilene.mp3"
alias amongus="${AUDIO_COMM} ${PREFIX_FOLDER}/amongus.mp3"
alias boanoite="${AUDIO_COMM} ${PREFIX_FOLDER}/boanoite.mp3"
alias parabens="${AUDIO_COMM} ${PREFIX_FOLDER}/para_bens.mp3"
alias deluvio="${AUDIO_COMM} ${PREFIX_FOLDER}/deluvio.mp3"
alias ttz="${AUDIO_COMM} ${PREFIX_FOLDER}/tistreza.mp3"
alias careless="${AUDIO_COMM} ${PREFIX_FOLDER}/careless.mp3"
alias fino="${AUDIO_COMM} ${PREFIX_FOLDER}/fino.mp3"
alias dwtd="${AUDIO_COMM} ${PREFIX_FOLDER}/dumbways.mp3"
alias baiano="${AUDIO_COMM} ${PREFIX_FOLDER}/olhaobaiano.mp3"
alias verdade="${AUDIO_COMM} ${PREFIX_FOLDER}/everdade.mp3"
alias racismo="${AUDIO_COMM} ${PREFIX_FOLDER}/racismo.mp3"
alias bob="${AUDIO_COMM} ${PREFIX_FOLDER}/bob.mp3"
alias treta="${AUDIO_COMM} ${PREFIX_FOLDER}/treta.mp3"
alias manga="${AUDIO_COMM} ${PREFIX_FOLDER}/zedamanga.mp3"
alias naofalacmg="${AUDIO_COMM} ${PREFIX_FOLDER}/naofalacmg.mp3"
alias calma="${AUDIO_COMM} ${PREFIX_FOLDER}/calma.mp3"
alias doneida="${AUDIO_COMM} ${PREFIX_FOLDER}/doneida.mp3"
alias magia="${AUDIO_COMM} ${PREFIX_FOLDER}/magia.mp3"
alias fogo="${AUDIO_COMM} ${PREFIX_FOLDER}/fogo.mp3"
alias culo="${AUDIO_COMM} ${PREFIX_FOLDER}/culo.mp3"

function audios {

	if [[ $1 == "-e" ]]; then
		sublime ${PREFIX_FOLDER}/../audios.sh
		open ${PREFIX_FOLDER}
		return
	fi

	# declare -a arr=("" )
	# for i in "${arr[@]}"; do
	#    echo "$i"
	# done
	echo "Meme de audios. Basta executar no terminal:"
	echo "   pain     	Girei"
	echo "   tosse    	tosseVeia"
	echo "   uol      	uOOL (maicol djeqson)"
	echo "   pdm      	pdm (pe de moleque)"
	echo "   prb      	PARABAINS"
	echo "   dmad     	2milanosdepois"
	echo "   lgl      	legal"
	echo "   blc      	bemloco"
	echo "   empt     	empolgante"
	echo "   aiai     	aiai"
	echo "   cceb     	cceb (como vc eh burro cara, que loucura)"
	echo "   vfmb     	vfmb (vc fala de uma maneira burra)"
	echo "   chines   	pqnaotrabaia"
	echo "   fdpoc    	filadaputaoce"
	echo "   kdoc     	cadeoce"
	echo "   pqntr    	poquenaotrabaia"
	echo "   tsc      	vaitomasuagu"
	echo "   enam      	eu nao aguENTO MAAAAAIS!"
	echo "   acsl      	Aham Claúdia Senta lá"
	echo "   srjb      	Serjão Berranteiro - MiaAAU AAUUHH"
	echo "   disg      	DISGRAÇAAAAAAAAAAAAAAAAAA"
	echo "   tstn    	Teoricamente sim... Teoricamente Nao"
	echo "   ceb    	Ce é o bichao mesmo ein doido!"
	echo "   cafe    	vai um cafezinho aí, o FILA da PUTA!"
	echo "   chtr      	Musica triste do chaves"
	echo "   arnold    	Different Strokes - arnold"
	echo "   entl    	Eu não to loco! - Alborghetti"
	echo "   uepa    	UEPAAAA - Ratinho"
	echo "   dlc    	Ai que diliça - Mickey"
	echo "   heman    	NHEEHEHEHEHE Eu vo bota na tua bunda He-Man!"
	echo "   tuab    	NHEEHEHEHEHE Eu vo bota na tua bunda!"
	echo "   galocego  	por causo de agressão de corpo em cima de trabalho"
	echo "           	pra fazer se transformar em cobra, me disrruga tudo"
	echo "           	minha pele sendo que eu nao mereço isso"
	echo "   jubileu	O Jubileu está esquisito hoje, eu tenho medo"
	echo "   tncp   	Tomo no cu, HAHAHAHAHAHA! - Papagaio"
	echo "   tcdsv     	Toma conta da sua vida!"
	echo "   jos     	Piano Jo Soares"
	echo "   taporra	TA PORRA MENÓ!"
	echo "   afdp   	AAAAAAAAAAAAAA FILHO DA PUTA!"
	echo "   abacaxi   	nao, nao, deus me livre... enfia um abacaxi no"
	echo "          	meu cu, mas nao me mete nisso!"
	echo "   mdms   	Meu Deus, meu senhor... Me ajuda, por favor!"
	echo "   tomei   	eu axo que eu.... tomei no cu!"
	echo "   globor   	Abertura do globo rural"
	echo "   selasque	Se lasque - Tiringa"
	echo "   searrombe	Se arrombe - Tiringa"
	echo "   miranha	Tema miranha meme"
	echo "   fail1  	The Lion Sleeps Tonight - distorcido"
	echo "   fail2  	The Lion Sleeps Tonight"
	echo "   arrea  	arrea! arrea! arrea a mao na minha cara, arrea!"
	echo "   borabill  	Bora Bill!!!!"
	echo "   borafi  	Bora fi do Bill!!!!"
	echo "   boramuie  	Bora muié do Bill!!!!"
	echo "   possop   	Posso Perguntar? - Show do Milhão"
	echo "   tchau   	Tchau Pessoal, até a próxima! - Show do Milhão"
	echo "   valemil   	Valendo Mil reais! - Show do Milhão"
	echo "   valeum   	Valendo um Milhão de reais! - Show do Milhão"
	echo "   vcent   	Você entendeu a pergunta? - Show do Milhão"
	echo "   toguro   	Musica triste do Toguro"
	echo "   sqlvh   	Senta que la vem história"
	echo "   marilene  	Olá Marilene!"
	echo "   amongus  	Tema Among Us"
	echo "   boanoite  	Boa noite é a cabeça da minha pi.."
	echo "   parabens  	Vou resumir em duas palavras: PARA BENS!"
	echo "   deluvio  	UUUUUUUUUUU.... Vai cair um delúvio!!!"
	echo "   careless  	Começo de 'Careless Whisper'"
	echo "   fino   	Fino señores 🗿🍷"
	echo "   dwtd   	Dumb Ways To Die"
	echo "   baiano   	Olha o Baiano - smzinho"
	echo "   verdade   	É verade... quer dizer, as vezes não..."
	echo "   racismo   	Oi racismo, bom dia!"
	echo "   bob    	Is This Love - inicio"
	echo "   treta    	Estou sentindo uma treta! shhhhhhhh"
	echo "   manga    	AHH! AHHH! zé da manga!"
	echo "   naofalacmg	Eu ja falei pra nao falar cmg - tropa de elite 2"
	echo "   calma  	O moreno ta ignorante, tenha calma moreno"
	echo "   doneida	Do Neida - Principe Ouro Negro"
	echo "   magia  	Não cite a Magia Profunda para mim!"
	echo "   fogo   	Ta pegando fogo bixo!"
	echo "   culo   	Yo la cago tanto que hasta me sorprende que no me llamo culo"
}


